### ISSUE TITLE
How to place F&O order?

### ISSUE THREAD

**Issue by ramesh8v** [swapniljariwala/zerodha#1]
Hi,

You have done an amazing job. 
I'm well aware that you mentioned F&O order will be added in future, changing SBIN-Eq with SBIN-FO will work (just curious)? 

Thanks
Ramesh

**Comment by swapniljariwala** [comment]
I havent tried this but here's how it should work

Try symbol like -
For options
NIFTY16MAR7700CE
Breakdown-
NIFTY- Symbol
16 - 2016
MAR - month
7700 - Strike Price
CE - (Call European)

For Futures
"NIFTY16APRFUT"

**Comment by swapniljariwala** [comment]
Yes something similar needs to be done. I just need to see code again and
request header..
But just cant find time :(
Let me know if you crack this
