### ISSUE TITLE
login_step1 is not working

### ISSUE THREAD

**Issue by preposturous** [swapniljariwala/zerodha#3]
Hi ,

Thanks for making this code public . I was trying it out but this code doesn't seem to work at the login_step1 stage itself. 
There are some merge issues in module.py too in the latest config . Can you please provide the working copy of the module.py 

Regards,

**Comment by swapniljariwala** [comment]
Things have changed on zerodha's website a lot since I wrote this last time. I will need to change somethings in order to get this working.

**Comment by swapniljariwala** [comment]
This is resolved for now. I might not develop this further till I come up with better design (and test cases :P).
This may break again in future if there's a change in kite.zerodha.com, Its better to use zerodha api if you are doing something mission critical.
