### ISSUE TITLE
Can we place AMO through this?

### ISSUE THREAD

**Issue by potholiday** [swapniljariwala/zerodha#5]
I want to automate my After Market Orders (AMO) can we place AMO orders through this or are you planning to include this functionality in future update? I dont want to stay at my terminal for long time. Weekdays at nights I want to place 5-10 orders

**Comment by swapniljariwala** [comment]
Hi,
in file https://github.com/swapniljariwala/zerodha/blob/master/broker/module.py
you just need to change param['variety'] = 'regular' to 'amo on line 146.
I know this is not ideal solution, but it should work for now.

**Comment by potholiday** [comment]
Thanks for the solution and keep up the good work :)
